name: "Build"

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 6.0
    
    - name: Restore packages
      run: dotnet restore

    - name: Build app
      run: dotnet build --configuration Release --no-restore

    - name: Publish app for deploy
      run: dotnet publish --configuration Release --no-build

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
    #   with:
    #     context: .
    #     file: ./.github/workflows/Dockerfile
    #     platforms: ${{ matrix.platforms }}
    #     push: true
    #     outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=My multi-arch image

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: ScienceTrack
        path: /home/runner/work/ScienceTrack_Backend/ScienceTrack_Backend/ScienceTrack/bin/Release/net8.0/publish/
